"""Test migration after cleanup

Revision ID: b9704b3a6f93
Revises: 3c66e53054e1
Create Date: 2025-09-02 17:34:25.047772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9704b3a6f93'
down_revision = '3c66e53054e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker_backup')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_is_deleted'))
        batch_op.drop_column('project_name')

    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracker_new_onboarded'))
        batch_op.drop_index(batch_op.f('ix_tracker_new_request_id'))
        batch_op.drop_index(batch_op.f('ix_tracker_new_student_id'))
        batch_op.drop_index(batch_op.f('ix_tracker_onboarded'))
        batch_op.drop_index(batch_op.f('ix_tracker_request_id'))
        batch_op.drop_index(batch_op.f('ix_tracker_student_id'))
        batch_op.drop_column('onboarded_student_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarded_student_ids', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_tracker_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracker_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracker_onboarded'), ['onboarded'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracker_new_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracker_new_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracker_new_onboarded'), ['onboarded'], unique=False)

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_requirements_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('tracker_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('email_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ### 